### ISSUE TITLE
Ensure nix-shell is usable and useful

### ISSUE THREAD

**Issue by samueldr** [fly-apps/rails-nix#21]

**Comment by jsierles** [comment]
One issue I ran into when playing with `nix-shell`.

Ideally you can use `bundlerEnv` and `bundix` because it helps you install gems with native dependencies (postgres, nokogiri, etc). If you try to use `bundle` on its own, you need to know how to install these dependencies. So maybe it's worth exploring how to do the deps stuff using a custom command that would do `bundle && bundix`, then somehow reevaluate the shell so we get the correct environment.

If we decided it's too much work to support bundix, we need to set `GEM_HOME` and such, and figure out how to get the right native deps installed. That may not even do the trick given that some have specific build instructions in Nix for darwin.

**Comment by jsierles** [comment]
A starter for this was done in https://github.com/fly-apps/nix-base/pull/3. We can open more specific tickets for nodejs support.
