### ISSUE TITLE
grpc gem build failure

### ISSUE THREAD

**Issue by jsierles** [fly-apps/rails-nix#23]
This gem changed its `extconf.rb` so the [substitution here will no longer work](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ruby-modules/gem-config/default.nix#L312). What should be the correct approach for fixing this?

```
[CXX]     Compiling src/core/lib/profiling/stap_timers.cc
mkdir -p `dirname /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/src/core/lib/profiling/stap_timers.o`
clang++ -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -DGRPC_XDS_USER_AGENT_NAME_SUFFIX="\"RUBY\""  -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="\"1.42.0\""  -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch arm64  -Ithird_party/zlib   -std=c++11 -stdlib=libc++   -fno-exceptions -MMD -MF /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/src/core/lib/profiling/stap_timers.dep -c -o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/src/core/lib/profiling/stap_timers.o src/core/lib/profiling/stap_timers.cc
[AR]      Creating /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/libs/opt/libz.a
mkdir -p `dirname /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/libs/opt/libz.a`
rm -f /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/libs/opt/libz.a
libtool -o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/libs/opt/libz.a /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/compress.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/crc32.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/deflate.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzclose.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzlib.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzread.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzwrite.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/infback.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inffast.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inflate.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inftrees.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/trees.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/uncompr.o /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/zutil.o
make: libtool: No such file or directory
make: *** [Makefile:2503: /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0/src/ruby/ext/grpc/libs/opt/libz.a] Error 127
make: *** Waiting for unfinished jobs....
make: Leaving directory '/nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/77bjl5185g1rxq0g7m868j5b7izvxanl-ruby-2.7.5/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0 for inspection.
Results logged to /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/extensions/arm64-darwin-20/2.7.0/grpc-1.42.0/gem_make.out
error: builder for '/nix/store/l8cgfwdl91g8gq9fgi7g22nnnwl56gd1-ruby2.7.5-grpc-1.42.0.drv' failed with exit code 1;
       last 10 log lines:
       >  --with-make-prog
       >       --without-make-prog
       >    --srcdir=.
       >     --curdir
       >       --ruby=/nix/store/77bjl5185g1rxq0g7m868j5b7izvxanl-ruby-2.7.5/bin/$(RUBY_BASE_NAME)
       >
       > extconf failed, exit code 1
       >
       > Gem files will remain installed in /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/gems/grpc-1.42.0 for inspection.
       > Results logged to /nix/store/6k1xk2b77fgqlbhmgfnyy7y6197gfmjh-ruby2.7.5-grpc-1.42.0/lib/ruby/gems/2.7.0/extensions/arm64-darwin-20/2.7.0/grpc-1.42.0/gem_make.out
       For full logs, run 'nix log /nix/store/l8cgfwdl91g8gq9fgi7g22nnnwl56gd1-ruby2.7.5-grpc-1.42.0.drv'.
error: 1 dependencies of derivation '/nix/store/6wlz359basx4nx83xkwbrb9jvcgmbq7c-development.drv' failed to build
```

**Comment by jsierles** [comment]
I attempted using this overlay to fix the build:

```
final: super:
{
  grpc = super.grpc.overrideAttrs (old: {
    postPatch = ''
      substituteInPlace Makefile \
        --replace '-Wno-invalid-source-encoding' ""
    '' + lib.optionalString stdenv.isDarwin ''
      substituteInPlace src/ruby/ext/grpc/extconf.rb \
        --replace "ENV['AR'] = 'libtool'" ""
      substituteInPlace src/ruby/ext/grpc/extconf.rb \
      --replace "ENV['ARFLAGS'] = '-o'" ""

    '';
  });
}
```

and then in shell.nix

```
{ pkgs ? (import ./nixpkgs.nix {})}:

let
  newpkgs = pkgs.appendOverlays [
    (import ./overlay.nix)
  ];
  gems = newpkgs.bundlerEnv {
    name = "development";
    gemdir = ./.;
  };
in newpkgs.mkShell {
  buildInputs = [
    gems
    gems.wrappedRuby
  ];
}
```

This doesn't seem to perform the substitutions. What am I doing wrong?

**Comment by jsierles** [comment]
Related PR to the actual failure: https://github.com/NixOS/nixpkgs/pull/149901

I'm also curious - are there Darwin test runners for Nix? Would this build failure have been caught somehow by CI?

**Comment by samueldr** [comment]
A lot of questions packed in that issue :).

I have to front-load with an explanation of why I'll be talking about `gitaly`. The `grpc` gem config is maintained mainly due to its use in `gitaly`.

* * *

> I'm also curious - are there Darwin test runners for Nix? Would this build failure have been caught somehow by CI?

There is **continuous integration** for (almost) everything in Nixpkgs. Here's the link for `gitaly` for `x86_64-darwin`:

 - https://hydra.nixos.org/job/nixpkgs/trunk/gitaly.x86_64-darwin/all

We can see that the version update here causes issues:

 - First failure: https://hydra.nixos.org/build/165425510
 - "change set"  [b05d20 to bd3256](https://hydra.nixos.org/api/scmdiff?rev1=b05d2077ebe219f6a47825767f8bab5c6211d200&rev2=bd3256cf4f7a651e234403977fa29d4dfde255b8&branch=&type=git&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git)

I'll skip the *how*, it's hard and requires knowledge to really make sense, but we can assume the following PR is the cause of the "regression":

 - https://github.com/NixOS/nixpkgs/pull/156299
 - version upgrade: https://github.com/NixOS/nixpkgs/pull/156299/files#diff-f2d42c7e377a08333eda6c5062d3eb734fd3e0db0e2ca82c010b033cbb80e951R26

On this PR, I can see that ofborg wasn't invoked to build `gitaly` specifically; it was [for gitlab on x86_64-darwin](https://github.com/NixOS/nixpkgs/runs/4937287128), but it fails to evaluate, so nothing was built/tried to be built.

So to answer *“are there Darwin test runners”*, yes changes *can* be tested with some test infra, but getting everything tried-to-be-built is not necessarily trivial, and here `gitlab` not working on Darwin masked the slight regression.

**Comment by jsierles** [comment]
Yeah. So what would we do to fix it? I've run into this in few projects already, as that gem is pretty common.

**Comment by samueldr** [comment]
> I attempted using this overlay to fix the build:
>
> [...] 
> 
> This doesn't seem to perform the substitutions. What am I doing wrong?

This is because you're patching the C library's derivation, and not the gem config.

 - https://github.com/NixOS/nixpkgs/blob/3a7a5eed09415df114d4cabab99cb820d4f24c19/pkgs/development/libraries/grpc/default.nix

vs.

 - https://github.com/NixOS/nixpkgs/blob/4d0e6f06a6ed0b17007c3d58d9be4dd77369656d/pkgs/development/ruby-modules/gem-config/default.nix#L293-L316

The solution to this would look more like the `pg` fix in this repo:

 - https://github.com/fly-apps/rails-nix/blob/16c65e5d5956139b2682fc0f9af82c7bf55a3e35/default.nix#L10-L11

If you look closely, the overlay changes the `defaultGemConfig` attribute, by using the *update operator* on `defaultGemConfig` to replace the `pg` attribute, which in turn uses the *update operator* to customize the `postInstall` attribute.

If you need the solution, I can provide it, but I figure with what you have already you should be good to complete the thought.

**Comment by samueldr** [comment]
As far as **solving**, this is hard to do in a robust manner, but not harder to do locally than contributing upstream in Nixpkgs.

The main issue is that `extconf.rb` is changing across gem versions, but the gem config will technically be applied to any versions. It should be possible to fix by using `attrs.version` and `lib.versionOlder` or `lib.versionAtLeast`, and apply different fixes across versions.

An alternative could be to make the change "weirder", but more universal.

Changing `ENV['AR']\s*=` and `ENV['ARFLAGS']\s*=` both to `ENV['XXX'] =` would be *functionally equivalent* to removing the lines; the values would now be set to an environment variable that is not in use.

Another option could be to *append* to extconf.rb with the current values in the environment, but that becomes messy with escaping and such.

**Comment by jsierles** [comment]
Nice - that worked. Someday I will get good at this!

**Comment by jsierles** [comment]
Closing for now - a follow up can be done an an actual PR to Nixpkgs.
