### ISSUE TITLE
nixpkgs 21.11 is missing an important coreutils patch

### ISSUE THREAD

**Issue by jsierles** [fly-apps/rails-nix#24]
Some common gems like `rbtrace` will fail to compile on arm64-darwin without this coreutils patch: 

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/coreutils/fix-arm64-macos.patch

So we should probably track `unstable` for now, perhaps?

**Comment by samueldr** [comment]
We can.

I chose the stable release (21.11) as a way to explcitly show we are free to pick anything, including something where major version changes don't happen.

But since we're pinning to specific commits, we won't get surprised by software update. As long as the proper test infra and procedures are there to validate updates, it should be good.

The "unstable" in the name of the release is a bit misleading. Actual unstability is excessively rare. Previously I half-jokedly would have said it's the version numbers that are unstable, not the software. These days I say it should be named `nixos-rolling` rather than `nixos-unstable`.

So if you're fine with rolling releases, unstable is fine. And since we're doing due diligence and pinning a known good release, I wouldn't expect this to bite you at any point in time.

**Comment by jsierles** [comment]
I just pinned to the top of `unstable` but I assume that's what you meant by a 'known good release'. Like you say, as long as pinning is overall a good choice for us, we're good. But this raises a doubt about how we might go about managing pins. I'll post in another issue.
